# Generated by Django 4.1.2 on 2022-10-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="date",
            field=models.DateField(default="2022-10-10"),
        ),
        migrations.AlterField(
            model_name="blog", name="description", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="blog", name="title", field=models.CharField(max_length=200),
        ),
    ]
